services:
  - type: web
    name: direct-upi-pay
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma db push && node scripts/seed.mjs && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: AUTH_SECRET
        generateValue: true
      - key: QR_EXPIRATION_MINUTES
        value: "5"
